"""`lrs seed` — demo districts, textbooks, and learners. Design §8.7.

"A stack you have to hand-populate before you can see anything is a stack nobody
explores" (design line 1155). Course content is IMPORTED from the real intelligent
textbook repos (see catalog.py); this module is the generator and the writer.

TWO PROFILES
------------
`--demo`     §8.7's shape: one district, two schools, four sections, two books.
`--showcase` Eight districts, forty schools, ~4,000 learners across the whole
             textbook catalogue — every book with a committed learning graph.

WHAT IS REAL
------------
Concepts, prerequisite edges, taxonomy categories, chapter names, textbook titles and
MicroSim titles all come from the textbook repos. Learners, districts, schools,
sections, pages, quizzes and every mastery score are synthesised here.

Grade placement is NOT modelled. Schools are all high schools and books are assigned
to them round-robin, because the source learning graphs carry no book-level grade
metadata — 24 of 53 books have no grade signal at all, and what exists is malformed in
several. Inventing a grade band per book would put a plausible-looking lie in the
graph, so the demo declines to have an opinion.

WHAT THIS IS NOT
----------------
Design §8.7 seeds synthetic *statements* and lets the pipeline compress them into the
graph. That path does not exist: `processor` and `summarizer` are both unbuilt (cli.py
line 8), so nothing can turn a statement log into a summary vertex. This module writes
the summary vertices DIRECTLY, deviating from spec §4.3's "projections, always
reproducible by replaying the immutable statement log". These are reproducible only by
re-running this seeder.

That is why every node here carries `seeded: true` — it keeps the demo distinguishable
from a real projection by query rather than by memory, and makes the dataset removable
in one pass (`--clear`). When the summarizer lands, the honest migration is `--clear`
and replay, not reconciliation.

C-1 is respected: no `:Statement` vertex is created, ever.

WHY MASTERY IS NOT RANDOM
-------------------------
`mastery_score` is generated by propagating each learner's ability DOWN the DEPENDS_ON
DAG: a concept's expected mastery is scaled by how well its prerequisites went. Some
learners are given an explicit `gap` — a high-fan-out concept they never got — and the
damage flows to everything downstream of it.

This matters because it is the whole demo. Against uniform-random mastery, "which
unmastered prerequisite is blocking this student?" returns noise: a learner can fail
Osmosis while having aced Diffusion, and the graph is a pretty picture that answers
nothing. With propagation, the question has a real answer and the graph earns its
place. The data has to have the structure you claim to be able to find in it.
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from neo4j import Driver, GraphDatabase

from lrs.catalog import Book, load_catalog
from lrs.config import Settings

log = logging.getLogger(__name__)

Row = dict[str, Any]

# Fixed so two runs produce identical data. With MERGE on the §6.3 keys that makes the
# seeder idempotent: a re-run converges instead of duplicating.
RNG_SEED = 20260716

TERM_START = datetime(2025, 9, 2, tzinfo=UTC)
TERM_END = datetime(2025, 12, 19, tzinfo=UTC)

# The real taxonomy categories are per-book subject areas ("Cellular Energetics"),
# not a cognitive scale, so they cannot pick a Bloom level. Depth in the DAG can:
# a concept with many prerequisites behind it is asking for more than recall. This is
# a heuristic for demo colour, not a claim about the source material.
BLOOM_BY_DEPTH = ["remember", "understand", "apply", "analyze", "evaluate", "create"]

VERBS = [
    ("experienced", "http://adlnet.gov/expapi/verbs/experienced", "experienced"),
    ("answered", "http://adlnet.gov/expapi/verbs/answered", "answered"),
    ("attempted", "http://adlnet.gov/expapi/verbs/attempted", "attempted"),
    ("completed", "http://adlnet.gov/expapi/verbs/completed", "completed"),
    ("interacted", "http://adlnet.gov/expapi/verbs/interacted", "interacted"),
    ("mastered", "http://adlnet.gov/expapi/verbs/mastered", "mastered"),
]

# (label, share of cohort, ability mean, ability sd, term progress mean)
# Ability is P(success) on a concept whose prerequisites all went perfectly; the DAG
# walk in _mastery_for_student takes it down from there. Progress is the fraction of
# the book reached by the end of the simulated term — nobody finishes, which is both
# realistic and what makes "what's next for this learner" a question worth asking.
ARCHETYPES = [
    ("struggling", 0.22, 0.44, 0.09, 0.42),
    ("typical", 0.54, 0.68, 0.09, 0.56),
    ("advanced", 0.24, 0.88, 0.06, 0.72),
]

# Share of learners carrying an explicit prerequisite gap.
GAP_SHARE = 0.35

# Rows per write transaction. Each ConceptMastery row is one MERGE plus three MATCHes
# and three relationship MERGEs, so a transaction costs far more than the row payload
# suggests. 5000 overruns dbms.memory.transaction.total.max (1.4 GiB, derived from the
# 2G heap §6.3 sets) once the catalogue passes ~500k summary vertices. 1000 keeps peak
# transaction memory flat; the extra round trips cost seconds, not minutes.
WRITE_BATCH = 1000


DISTRICT_NAMES = [
    ("Riverbend Public Schools", "MN"),
    ("Lakeshore Area Schools", "MN"),
    ("Northfield Consolidated", "MN"),
    ("Prairie Valley Schools", "MN"),
    ("Cedar Hollow District", "WI"),
    ("Granite Ridge Schools", "WI"),
    ("Silverbrook Unified", "IA"),
    ("Maple Grove Area Schools", "IA"),
]

# Fictional, and obviously so to anyone who checks — no real district's data is here.
SCHOOL_NAMES = ["Washington", "Lincoln", "Roosevelt", "Kennedy", "Jefferson"]


@dataclass(frozen=True)
class Profile:
    """A dataset size. Content comes from the catalogue; this scales tenancy over it."""

    name: str
    districts: int
    schools_per_district: int
    sections_per_course: int
    students_per_section: int
    # None = every book with a committed learning graph.
    books: tuple[str, ...] | None


# §8.7's shape: "one district, two schools, four sections". Two books, one per school,
# two sections each. xapi-course is the thematic pick — the LRS measuring the very book
# that explains xAPI — and biology is the one most teachers can read over your shoulder.
DEMO = Profile(
    "demo",
    districts=1,
    schools_per_district=2,
    sections_per_course=2,
    students_per_section=25,
    books=("xapi-course", "biology"),
)

# The whole catalogue: 53 books across 8 districts, 3 sections each, ~4,000 learners.
SHOWCASE = Profile(
    "showcase",
    districts=8,
    schools_per_district=5,
    sections_per_course=3,
    students_per_section=25,
    books=None,
)

PROFILES = {"demo": DEMO, "showcase": SHOWCASE}


def _driver(cfg: Settings) -> Driver:
    return GraphDatabase.driver(cfg.neo4j_uri, auth=(cfg.neo4j_user, cfg.neo4j_password))


def _slug(text: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in text]
    return "".join(keep).strip("-").replace("--", "-")


def _ts(rng: random.Random, lo: float = 0.0, hi: float = 1.0) -> datetime:
    """An instant inside a [lo, hi] window of the simulated term."""
    span = (TERM_END - TERM_START).total_seconds()
    return TERM_START + timedelta(seconds=rng.uniform(lo * span, hi * span))


def _concept_order(book: Book) -> list[tuple[str, str, str, list[str], int]]:
    """(concept_id, label, category, prereqs, chapter_index) in TOPOLOGICAL order.

    Topological, NOT chapter order. catalog.py groups concepts into chapters by taxonomy
    category, and that grouping does not preserve the topological order it was built
    from — a taxonomy category is a subject area, not a teaching sequence, so a concept
    in chapter 1 can depend on one in chapter 3. The mastery walk must see every
    prerequisite before the concept needing it, so it follows book["concepts"] and
    carries the chapter index along only to place events within the term.
    """
    chapter_of = {c[0]: i for i, (_t, cs) in enumerate(book["chapters"]) for c in cs}
    return [
        (cid, label, tax, list(deps), chapter_of[cid]) for cid, label, tax, deps in book["concepts"]
    ]


def _content(rng: random.Random, books: list[Book]) -> dict[str, Any]:
    """Textbooks, versions, chapters, pages, microsims, quizzes, questions, concepts."""
    textbooks: list[Row] = []
    versions: list[Row] = []
    chapters: list[Row] = []
    pages: list[Row] = []
    microsims: list[Row] = []
    microsim_versions: list[Row] = []
    quizzes: list[Row] = []
    questions: list[Row] = []
    concepts: list[Row] = []
    depends_on: list[Row] = []
    covers: list[Row] = []
    # textbook_id -> ordered page ids, used later to place engagement in book order
    pages_by_book: dict[str, list[str]] = {}
    questions_by_book: dict[str, list[Row]] = {}
    unplaceable: list[str] = []

    for book in books:
        tid = book["textbook_id"]
        textbooks.append(
            {
                "textbook_id": tid,
                "title": book["title"],
                "repo_url": book["repo_url"],
            }
        )
        # Two versions per book. Districts alternate between them, which is what makes
        # IN_CONTEXT_OF worth having: "did v2 actually help?" is an A/B question (§8)
        # you can only ask if the summaries are attributed to a version.
        for n, semver in enumerate(("1.4.0", "2.0.0"), start=1):
            versions.append(
                {
                    "version_id": f"{tid}-v{n}",
                    "semver": semver,
                    "git_sha": f"{rng.getrandbits(160):040x}",
                    "published_at": TERM_START - timedelta(days=60 - 30 * n),
                    "textbook_id": tid,
                }
            )

        for cid, label, category, prereqs, _ci in _concept_order(book):
            concepts.append({"concept_id": cid, "label": label, "taxonomy_category": category})
            for p in prereqs:
                depends_on.append({"from": cid, "to": p})

        pages_by_book[tid] = []
        for ci, (chapter_title, chapter_concepts) in enumerate(book["chapters"]):
            chapter_id = f"{tid}-ch{ci + 1:02d}"
            chapters.append(
                {
                    "chapter_id": chapter_id,
                    "order": ci + 1,
                    "title": chapter_title,
                    "textbook_id": tid,
                }
            )
            # Pages carry 2 concepts each — a real page teaches a couple of related
            # ideas, and a 1:1 page:concept mapping would make COVERS meaningless.
            for pi in range(0, len(chapter_concepts), 2):
                group = chapter_concepts[pi : pi + 2]
                title = " and ".join(c[1] for c in group)
                page_id = f"{chapter_id}-p{pi // 2 + 1:02d}"
                pages.append(
                    {
                        "page_id": page_id,
                        "path": f"/{_slug(chapter_title)}/{_slug(group[0][1])}/",
                        "title": title,
                        "word_count": rng.randrange(450, 1700),
                        "chapter_id": chapter_id,
                    }
                )
                pages_by_book[tid].append(page_id)
                for c in group:
                    covers.append({"from_id": page_id, "label": "Page", "to": c[0]})

            quiz_id = f"{chapter_id}-quiz"
            quizzes.append(
                {
                    "quiz_id": quiz_id,
                    "title": f"{chapter_title} — Check Your Understanding",
                    "page_id": pages_by_book[tid][-1],
                }
            )
            questions_by_book.setdefault(tid, [])
            for qi, (cid, _label, _category, prereqs) in enumerate(chapter_concepts[:8]):
                # Deeper in the DAG -> higher on Bloom. See BLOOM_BY_DEPTH.
                depth = min(len(BLOOM_BY_DEPTH) - 1, len(prereqs) + rng.randint(0, 1))
                q = {
                    "question_id": f"{quiz_id}-q{qi + 1:02d}",
                    "bloom_level": BLOOM_BY_DEPTH[depth],
                    "concept_ref": cid,
                    "quiz_id": quiz_id,
                }
                questions.append(q)
                questions_by_book[tid].append(q)
                covers.append({"from_id": q["question_id"], "label": "Question", "to": cid})

        # A MicroSim is embedded on a page that teaches one of its concepts.
        page_of_concept = {c["to"]: c["from_id"] for c in covers if c["label"] == "Page"}
        for msid, title, ms_type, status, ms_concepts in book["microsims"]:
            # catalog.py's matcher is deliberately conservative, so a real sim whose
            # title matches no concept label arrives with an empty list. It cannot be
            # placed: EMBEDS needs a page, and the page is chosen by concept. Guessing
            # a page would put a false claim in the graph — that THIS page teaches this
            # sim — so it is dropped instead, and counted (never silently).
            placed = [c for c in ms_concepts if c in page_of_concept]
            if not placed:
                unplaceable.append(title)
                continue
            microsims.append(
                {
                    "microsim_id": msid,
                    "type": ms_type,
                    "title": title,
                    "status": status,
                    "page_id": page_of_concept[placed[0]],
                }
            )
            microsim_versions.append(
                {
                    "msv_id": f"{msid}-v1",
                    "semver": "1.0.0",
                    "git_sha": f"{rng.getrandbits(160):040x}",
                    "microsim_id": msid,
                }
            )
            for ms_concept in placed:
                covers.append({"from_id": msid, "label": "MicroSim", "to": ms_concept})

    if unplaceable:
        log.info(
            "%d of %d MicroSims had no confident concept match and were not placed (e.g. %s)",
            len(unplaceable),
            len(unplaceable) + len(microsims),
            ", ".join(unplaceable[:3]),
        )

    return {
        "textbooks": textbooks,
        "versions": versions,
        "chapters": chapters,
        "pages": pages,
        "microsims": microsims,
        "microsim_versions": microsim_versions,
        "quizzes": quizzes,
        "questions": questions,
        "concepts": concepts,
        "depends_on": depends_on,
        "covers": covers,
        "verbs": [{"verb_id": v, "iri": i, "display": d} for v, i, d in VERBS],
        "_pages_by_book": pages_by_book,
        "_questions_by_book": questions_by_book,
    }


def _gap_candidates(book: Book) -> list[str]:
    """Concepts worth failing: the ones with the most direct dependents.

    A gap on a leaf concept teaches the demo nothing — nothing is downstream of it.
    A gap on Diffusion takes out Osmosis, Passive Transport and Active Transport, and
    THAT is the query worth running in front of a teacher.
    """
    fan_out: dict[str, int] = {}
    for _cid, _label, _cat, prereqs, _ci in _concept_order(book):
        for p in prereqs:
            fan_out[p] = fan_out.get(p, 0) + 1
    return sorted([c for c, n in fan_out.items() if n >= 2], key=lambda c: -fan_out[c])


def _tenancy(rng: random.Random, profile: Profile, books: list[Book]) -> dict[str, Any]:
    districts: list[Row] = []
    schools: list[Row] = []
    courses: list[Row] = []
    sections: list[Row] = []
    instructors: list[Row] = []
    students: list[Row] = []
    enrollments: list[Row] = []
    deploys: list[Row] = []

    student_n = 0
    for di in range(profile.districts):
        name, state = DISTRICT_NAMES[di % len(DISTRICT_NAMES)]
        did = f"district-{di + 1:02d}"
        districts.append(
            {
                "district_id": did,
                "name": name,
                "state": state,
                "timezone": "America/Chicago",
            }
        )
        # Districts alternate textbook versions — the A/B seam of §8.
        version_n = (di % 2) + 1

        for n in range(profile.schools_per_district):
            sid = f"{did}-school-{n + 1}"
            schools.append(
                {
                    "school_id": sid,
                    "name": f"{SCHOOL_NAMES[n % len(SCHOOL_NAMES)]} High School",
                    # Every school is 9-12: the catalogue spans kindergarten reading to
                    # semiconductor physics, but the source learning graphs carry no
                    # book-level grade metadata, so placing books by band would mean
                    # inventing one. See this module's docstring.
                    "grade_band": "9-12",
                    "district_id": did,
                }
            )

        # Books are dealt round-robin across districts, then across that district's
        # schools. Every book in the catalogue lands in exactly one course somewhere,
        # which is what keeps "53 textbooks in one graph" true rather than decorative.
        for bi, book in enumerate(books[di :: profile.districts]):
            tid = book["textbook_id"]
            sid = f"{did}-school-{bi % profile.schools_per_district + 1}"
            cid = f"{sid}-{tid}"
            courses.append(
                {
                    "course_id": cid,
                    "title": book["title"],
                    "subject": book["subject"],
                    "school_id": sid,
                }
            )

            for p in range(profile.sections_per_course):
                sec_id = f"{cid}-sec{p + 1}"
                sections.append(
                    {
                        "section_id": sec_id,
                        "period": p + 1,
                        "term": "fall",
                        "academic_year": "2025-2026",
                        "course_id": cid,
                    }
                )
                deploys.append({"section_id": sec_id, "version_id": f"{tid}-v{version_n}"})
                instructors.append(
                    {
                        "instructor_key": f"inst-{len(instructors) + 1:04d}",
                        "role": "teacher",
                        "section_id": sec_id,
                    }
                )

                for _ in range(profile.students_per_section):
                    student_n += 1
                    # §4.1: student_key is pseudonymous and "No PII stored here". The
                    # vault (§6.4) is the only place a roster id maps to one of these,
                    # so the seeder never invents a name to put in the graph.
                    key = f"stu-{student_n:05d}"
                    students.append({"student_key": key, "grade_level": 10})
                    enrollments.append(
                        {
                            "student_key": key,
                            "section_id": sec_id,
                            "enrolled_at": TERM_START,
                            "status": "active",
                            # not written to the graph; used to build summaries
                            "_textbook_id": tid,
                            "_version_id": f"{tid}-v{version_n}",
                        }
                    )

    return {
        "districts": districts,
        "schools": schools,
        "courses": courses,
        "sections": sections,
        "instructors": instructors,
        "students": students,
        "enrollments": enrollments,
        "deploys": deploys,
    }


def _summaries(
    rng: random.Random, content: dict[str, Any], tenancy: dict[str, Any], books: list[Book]
) -> dict[str, list[Row]]:
    """Walk each learner down their book's DAG. See this module's docstring."""
    by_book = {b["textbook_id"]: b for b in books}
    flat = {tid: _concept_order(b) for tid, b in by_book.items()}
    gaps_by_book = {tid: _gap_candidates(b) for tid, b in by_book.items()}
    concept_page = {c["to"]: c["from_id"] for c in content["covers"] if c["label"] == "Page"}
    # Inverted once, not per learner. Scanning `covers` inside the per-page loop made
    # this function O(learners x pages x covers) — ~10^10 operations on the full
    # catalogue, and 90% of the build time.
    concepts_of_page: dict[str, list[str]] = {}
    for c in content["covers"]:
        if c["label"] == "Page":
            concepts_of_page.setdefault(c["from_id"], []).append(c["to"])

    mastery: list[Row] = []
    page_engagement: list[Row] = []
    question_response: list[Row] = []
    weights = [a[1] for a in ARCHETYPES]

    for enrollment in tenancy["enrollments"]:
        key = enrollment["student_key"]
        tid = enrollment["_textbook_id"]
        version_id = enrollment["_version_id"]
        concepts = flat[tid]

        _label, _share, mean, sd, progress_mean = rng.choices(ARCHETYPES, weights)[0]
        ability = min(0.98, max(0.08, rng.gauss(mean, sd)))
        progress = min(1.0, max(0.15, rng.gauss(progress_mean, 0.1)))
        reached = concepts[: max(3, int(len(concepts) * progress))]

        gaps: set[str] = set()
        if rng.random() < GAP_SHARE:
            candidates = [c for c in gaps_by_book[tid] if c in {r[0] for r in reached}]
            if candidates:
                gaps.add(candidates[rng.randrange(min(6, len(candidates)))])

        scores: dict[str, float] = {}
        touched_pages: set[str] = set()

        for cid, _lbl, _cat, prereqs, chapter_i in reached:
            known = [scores[p] for p in prereqs if p in scores]
            # A concept is only as reachable as its shakiest foundations. The 0.35 floor
            # keeps a total prerequisite failure from forcing mastery to exactly zero —
            # learners do pick things up out of order, just badly.
            prereq_factor = 0.35 + 0.65 * (sum(known) / len(known) if known else 1.0)
            score = ability * prereq_factor
            if cid in gaps:
                score *= 0.3
            score = min(0.99, max(0.02, rng.gauss(score, 0.07)))
            scores[cid] = score

            attempts = rng.randint(4, 26)
            successes = min(attempts, max(0, round(attempts * score + rng.gauss(0, 1))))
            # Progress through the term tracks progress through the book.
            lo = chapter_i / max(1, len(by_book[tid]["chapters"]))
            first = _ts(rng, lo * 0.8, min(1.0, lo * 0.8 + 0.25))
            mastery.append(
                {
                    "student_key": key,
                    "concept_id": cid,
                    "mastery_score": round(score, 3),
                    "evidence_count": attempts,
                    "attempts": attempts,
                    "successes": successes,
                    "first_seen": first,
                    "last_seen": first + timedelta(days=rng.randint(1, 21)),
                    "statements_compressed": rng.randint(18, 26),
                    "version_id": version_id,
                }
            )
            touched_pages.add(concept_page[cid])

        for page_id in touched_pages:
            first = _ts(rng)
            # Struggling learners re-read: revisit and dwell rise as mastery falls. This
            # is the correlation that makes "which pages are costing time without
            # producing mastery?" a real question rather than a coin flip.
            page_scores = [scores[c] for c in concepts_of_page.get(page_id, ()) if c in scores]
            difficulty = 1.0 - (sum(page_scores) / len(page_scores) if page_scores else 0.5)
            page_engagement.append(
                {
                    "student_key": key,
                    "page_id": page_id,
                    "dwell_ms_total": int(rng.randrange(40_000, 400_000) * (0.6 + difficulty)),
                    "revisit_count": max(1, round(rng.gauss(1 + 5 * difficulty, 1))),
                    "scroll_depth_max": round(min(1.0, rng.uniform(0.35, 1.0)), 2),
                    "first_seen": first,
                    "last_seen": first + timedelta(days=rng.randint(1, 30)),
                    "statements_compressed": rng.randint(18, 26),
                    "version_id": version_id,
                }
            )

        answerable = [q for q in content["_questions_by_book"][tid] if q["concept_ref"] in scores]
        for q in rng.sample(answerable, min(8, len(answerable))):
            score = scores[q["concept_ref"]]
            attempts = rng.randint(1, 5)
            successes = min(attempts, max(0, round(attempts * score + rng.gauss(0, 0.6))))
            question_response.append(
                {
                    "student_key": key,
                    "question_id": q["question_id"],
                    "attempts": attempts,
                    "successes": successes,
                    "mean_score": round(score, 3),
                    # §4.3 names first_success_attempt. null is the honest value for a
                    # learner who never got it right; 0 would read as "first try".
                    "first_success_attempt": rng.randint(1, attempts) if successes else None,
                    "last_seen": _ts(rng),
                    "statements_compressed": rng.randint(18, 26),
                }
            )

    return {
        "mastery": mastery,
        "page_engagement": page_engagement,
        "question_response": question_response,
    }


# Every write MERGEs on a §6.3 key, so the seeder is idempotent by construction: the
# composite grain constraints turn a re-run into an upsert rather than a second vertex
# per grain — the same property the real summarizer will depend on.
_WRITES: list[tuple[str, str, str]] = [
    (
        "districts",
        "districts",
        """
        UNWIND $rows AS row
        MERGE (d:District {district_id: row.district_id})
        SET d += {name: row.name, state: row.state, timezone: row.timezone, seeded: true}
    """,
    ),
    (
        "schools",
        "schools",
        """
        UNWIND $rows AS row
        MERGE (s:School {school_id: row.school_id})
        SET s += {name: row.name, grade_band: row.grade_band, seeded: true}
        WITH s, row MATCH (d:District {district_id: row.district_id})
        MERGE (d)-[:HAS_SCHOOL]->(s)
    """,
    ),
    (
        "courses",
        "courses",
        """
        UNWIND $rows AS row
        MERGE (c:Course {course_id: row.course_id})
        SET c += {title: row.title, subject: row.subject, seeded: true}
        WITH c, row MATCH (s:School {school_id: row.school_id})
        MERGE (s)-[:OFFERS]->(c)
    """,
    ),
    (
        "sections",
        "sections",
        """
        UNWIND $rows AS row
        MERGE (s:Section {section_id: row.section_id})
        SET s += {period: row.period, term: row.term,
                  academic_year: row.academic_year, seeded: true}
        WITH s, row MATCH (c:Course {course_id: row.course_id})
        MERGE (c)-[:HAS_SECTION]->(s)
    """,
    ),
    (
        "instructors",
        "instructors",
        """
        UNWIND $rows AS row
        MERGE (i:Instructor {instructor_key: row.instructor_key})
        SET i += {role: row.role, seeded: true}
        WITH i, row MATCH (s:Section {section_id: row.section_id})
        MERGE (i)-[:TEACHES]->(s)
    """,
    ),
    (
        "students",
        "students",
        """
        UNWIND $rows AS row
        MERGE (s:Student {student_key: row.student_key})
        SET s += {grade_level: row.grade_level, seeded: true}
    """,
    ),
    (
        "enrollments",
        "enrollments",
        """
        UNWIND $rows AS row
        MATCH (st:Student {student_key: row.student_key})
        MATCH (se:Section {section_id: row.section_id})
        MERGE (st)-[e:ENROLLED_IN]->(se)
        SET e += {enrolled_at: row.enrolled_at, status: row.status}
    """,
    ),
    (
        "textbooks",
        "textbooks",
        """
        UNWIND $rows AS row
        MERGE (t:Textbook {textbook_id: row.textbook_id})
        SET t += {title: row.title, repo_url: row.repo_url, seeded: true}
    """,
    ),
    (
        "versions",
        "textbook versions",
        """
        UNWIND $rows AS row
        MERGE (v:TextbookVersion {version_id: row.version_id})
        SET v += {semver: row.semver, git_sha: row.git_sha,
                  published_at: row.published_at, seeded: true}
        WITH v, row MATCH (t:Textbook {textbook_id: row.textbook_id})
        MERGE (v)-[:VERSION_OF]->(t)
    """,
    ),
    (
        "deploys",
        "DEPLOYS edges",
        """
        UNWIND $rows AS row
        MATCH (s:Section {section_id: row.section_id})
        MATCH (v:TextbookVersion {version_id: row.version_id})
        MERGE (s)-[:DEPLOYS]->(v)
    """,
    ),
    (
        "concepts",
        "concepts",
        """
        UNWIND $rows AS row
        MERGE (c:Concept {concept_id: row.concept_id})
        SET c += {label: row.label, taxonomy_category: row.taxonomy_category, seeded: true}
    """,
    ),
    (
        "depends_on",
        "DEPENDS_ON edges",
        """
        UNWIND $rows AS row
        MATCH (a:Concept {concept_id: row.from})
        MATCH (b:Concept {concept_id: row.to})
        MERGE (a)-[:DEPENDS_ON]->(b)
    """,
    ),
    (
        "chapters",
        "chapters",
        """
        UNWIND $rows AS row
        MERGE (c:Chapter {chapter_id: row.chapter_id})
        SET c += {order: row.order, title: row.title, seeded: true}
        WITH c, row MATCH (t:Textbook {textbook_id: row.textbook_id})
        MERGE (t)-[:CONTAINS]->(c)
    """,
    ),
    (
        "pages",
        "pages",
        """
        UNWIND $rows AS row
        MERGE (p:Page {page_id: row.page_id})
        SET p += {path: row.path, title: row.title,
                  word_count: row.word_count, seeded: true}
        WITH p, row MATCH (c:Chapter {chapter_id: row.chapter_id})
        MERGE (c)-[:CONTAINS]->(p)
    """,
    ),
    (
        "microsims",
        "microsims",
        """
        UNWIND $rows AS row
        MERGE (m:MicroSim {microsim_id: row.microsim_id})
        SET m += {type: row.type, title: row.title, status: row.status, seeded: true}
        WITH m, row MATCH (p:Page {page_id: row.page_id})
        MERGE (p)-[:EMBEDS]->(m)
    """,
    ),
    (
        "microsim_versions",
        "microsim versions",
        """
        UNWIND $rows AS row
        MERGE (v:MicroSimVersion {msv_id: row.msv_id})
        SET v += {semver: row.semver, git_sha: row.git_sha, seeded: true}
        WITH v, row MATCH (m:MicroSim {microsim_id: row.microsim_id})
        MERGE (m)-[:HAS_VERSION]->(v)
    """,
    ),
    (
        "quizzes",
        "quizzes",
        """
        UNWIND $rows AS row
        MERGE (q:Quiz {quiz_id: row.quiz_id})
        SET q += {title: row.title, seeded: true}
        WITH q, row MATCH (p:Page {page_id: row.page_id})
        MERGE (p)-[:EMBEDS]->(q)
    """,
    ),
    (
        "questions",
        "questions",
        """
        UNWIND $rows AS row
        MERGE (q:Question {question_id: row.question_id})
        SET q += {bloom_level: row.bloom_level, concept_ref: row.concept_ref, seeded: true}
        WITH q, row MATCH (z:Quiz {quiz_id: row.quiz_id})
        MERGE (z)-[:CONTAINS]->(q)
    """,
    ),
    (
        "verbs",
        "verbs",
        """
        UNWIND $rows AS row
        MERGE (v:Verb {verb_id: row.verb_id})
        SET v += {iri: row.iri, display: row.display, seeded: true}
    """,
    ),
    (
        "mastery",
        "ConceptMastery vertices",
        """
        UNWIND $rows AS row
        MERGE (m:ConceptMastery {student_key: row.student_key, concept_id: row.concept_id})
        SET m += {mastery_score: row.mastery_score, evidence_count: row.evidence_count,
                  attempts: row.attempts, successes: row.successes,
                  first_seen: row.first_seen, last_seen: row.last_seen,
                  statements_compressed: row.statements_compressed, seeded: true}
        WITH m, row
        MATCH (s:Student {student_key: row.student_key})
        MATCH (c:Concept {concept_id: row.concept_id})
        MATCH (v:TextbookVersion {version_id: row.version_id})
        MERGE (s)-[:HAS_MASTERY]->(m)
        MERGE (m)-[:OF_CONCEPT]->(c)
        MERGE (m)-[:IN_CONTEXT_OF]->(v)
    """,
    ),
    (
        "page_engagement",
        "PageEngagement vertices",
        """
        UNWIND $rows AS row
        MERGE (p:PageEngagement {student_key: row.student_key, page_id: row.page_id})
        SET p += {dwell_ms_total: row.dwell_ms_total, revisit_count: row.revisit_count,
                  scroll_depth_max: row.scroll_depth_max, first_seen: row.first_seen,
                  last_seen: row.last_seen,
                  statements_compressed: row.statements_compressed, seeded: true}
        WITH p, row
        MATCH (s:Student {student_key: row.student_key})
        MATCH (pg:Page {page_id: row.page_id})
        MATCH (v:TextbookVersion {version_id: row.version_id})
        MERGE (s)-[:ENGAGED_WITH]->(p)
        MERGE (p)-[:SUMMARIZES]->(pg)
        MERGE (p)-[:IN_CONTEXT_OF]->(v)
    """,
    ),
    # No IN_CONTEXT_OF: §4.2 scopes that edge to {ConceptMastery, PageEngagement,
    # MicroSimEngagement}. QuestionResponse is deliberately absent from that list.
    (
        "question_response",
        "QuestionResponse vertices",
        """
        UNWIND $rows AS row
        MERGE (q:QuestionResponse {student_key: row.student_key, question_id: row.question_id})
        SET q += {attempts: row.attempts, successes: row.successes, mean_score: row.mean_score,
                  first_success_attempt: row.first_success_attempt, last_seen: row.last_seen,
                  statements_compressed: row.statements_compressed, seeded: true}
        WITH q, row
        MATCH (s:Student {student_key: row.student_key})
        MATCH (qn:Question {question_id: row.question_id})
        MERGE (s)-[:RESPONDED_TO]->(q)
        MERGE (q)-[:SUMMARIZES]->(qn)
    """,
    ),
]

_COVERS = """
    UNWIND $rows AS row
    MATCH (c:Concept {concept_id: row.to})
    CALL (row, c) {
      WITH row, c
      MATCH (n:Page {page_id: row.from_id}) WHERE row.label = 'Page'
      MERGE (n)-[:COVERS]->(c)
      UNION
      WITH row, c
      MATCH (n:MicroSim {microsim_id: row.from_id}) WHERE row.label = 'MicroSim'
      MERGE (n)-[:COVERS]->(c)
      UNION
      WITH row, c
      MATCH (n:Question {question_id: row.from_id}) WHERE row.label = 'Question'
      MERGE (n)-[:COVERS]->(c)
    }
"""


def clear(cfg: Settings) -> int:
    """Remove everything this seeder wrote, and nothing else.

    `seeded: true` is what makes this safe: a real projection written by the summarizer
    carries no such property and survives.

    CALL ... IN TRANSACTIONS, not a client-side batch loop. The whole delete is one
    logical statement, but Neo4j commits it every 1000 rows, so peak transaction memory
    stays flat no matter how large the dataset. A loop of `LIMIT 10000 DETACH DELETE`
    does NOT: each batch is one transaction, and on the full catalogue that blows
    dbms.memory.transaction.total.max (1.4 GiB, derived from the 2G heap §6.3 sets)
    before it finishes. This needs an autocommit session — IN TRANSACTIONS is illegal
    inside the managed transaction execute_query opens.
    """
    with _driver(cfg) as driver, driver.session() as session:
        result = session.run(
            "MATCH (n {seeded: true}) CALL (n) { DETACH DELETE n } IN TRANSACTIONS OF 1000 ROWS"
        )
        return int(result.consume().counters.nodes_deleted)


def build(profile: Profile, books: list[Book]) -> dict[str, Any]:
    """All rows for a profile. Pure — no I/O, so it is testable without a database."""
    rng = random.Random(RNG_SEED)
    content = _content(rng, books)
    tenancy = _tenancy(rng, profile, books)
    data: dict[str, Any] = {**content, **tenancy}
    data.update(_summaries(rng, content, tenancy, books))
    return data


def load_books(cfg: Settings, profile: Profile) -> list[Book]:
    """The catalogue this profile wants, from cfg.textbook_root."""
    root = Path(cfg.textbook_root).expanduser().resolve()
    books = load_catalog(root, only=list(profile.books) if profile.books else None)
    if not books:
        raise FileNotFoundError(
            f"no textbook learning graphs under {root}. Point LRS_TEXTBOOK_ROOT at the "
            f"directory holding the textbook repos (each needs "
            f"docs/learning-graph/learning-graph.csv)."
        )
    if profile.books:
        missing = set(profile.books) - {b["textbook_id"].removeprefix("tb-") for b in books}
        if missing:
            log.warning("profile %s wanted books not found: %s", profile.name, sorted(missing))
    log.info(
        "loaded %d textbooks from %s (%d concepts)",
        len(books),
        root,
        sum(len(b["concepts"]) for b in books),
    )
    return books


def seed(cfg: Settings, profile: Profile) -> dict[str, int]:
    """Write the demo graph. Idempotent — MERGE on the §6.3 keys."""
    data = build(profile, load_books(cfg, profile))
    counts: dict[str, int] = {}

    with _driver(cfg) as driver:
        for key, label, cypher in _WRITES:
            rows = data[key]
            for i in range(0, len(rows), WRITE_BATCH):
                driver.execute_query(cypher, rows=rows[i : i + WRITE_BATCH])
            counts[label] = len(rows)
            log.info("seeded %7d %s", counts[label], label)

        for i in range(0, len(data["covers"]), WRITE_BATCH):
            driver.execute_query(_COVERS, rows=data["covers"][i : i + WRITE_BATCH])
        counts["COVERS edges"] = len(data["covers"])
        log.info("seeded %7d %s", counts["COVERS edges"], "COVERS edges")

    return counts
